### ISSUE TITLE
When I try to upload to my chip, there is an error appear.

### ISSUE THREAD

**Issue by lucalauc** [gtalusan/PADIIoTStamp#2]
The error message as below:
Index error: could not find referenced tool name=arm-none-eabi-gcc version=4.8.3-2014q1 packager=realtek
Index error: could not find referenced tool name=ameba_tools version=1.0.8 packager=realtek
The current selected board needs the core 'realtek:arduino' that is not installed.

What else I have missed within the process.
Thank you very much!

**Comment by gtalusan** [comment]
Read the second line of the README.

**Comment by lucalauc** [comment]
Ya, I found that I need to put both your .json and ameba .json in perference setting after I post the question.

I am kend of stupid on it. Sorry for my careless act.

But I met another problem that as below.

Archiving built core (caching) in: 

> C:\Users\Myself\AppData\Local\Temp\arduino_cache_761933\core\core_padiiotstamp_ameba_padiiotstamp_OpenOCD_jlink_bd962ef21d8984eda6eaf62e1f26ec72.a
> Sketch uses 67476 bytes (2%) of program storage space. Maximum is 2499639 bytes.
> java.io.IOException: Cannot run program "/usr/local/bin/openocd": CreateProcess error=2, The System Cannot Find the File Specified.
> 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
> 	at processing.app.helpers.ProcessUtils.exec(ProcessUtils.java:26)
> 	at cc.arduino.packages.Uploader.executeUploadCommand(Uploader.java:129)
> 	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:207)
> 	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:78)
> 	at processing.app.SketchController.upload(SketchController.java:713)
> 	at processing.app.SketchController.exportApplet(SketchController.java:686)
> 	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2135)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.io.IOException: CreateProcess error=2, 系統找不到指定的檔案。
> 	at java.lang.ProcessImpl.create(Native Method)
> 	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
> 	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
> 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
> 	... 8 more
> An error occurred while uploading the sketch

Don't know what I can do to solve this problem.

It there any possible error I have made?

Thank you so much.

**Comment by lucalauc** [comment]
Or, which hardware you are using to connect PADI to the computer?

**Comment by gtalusan** [comment]
No worries, read the last line of Installation.  This was tested on macOS but should work on Linux.  For Windows you'll need to change around the paths that are pointed out in the configuration and potentially install OpenOCD.

**Comment by lucalauc** [comment]
Thanks for you quick response!
I see the purple one in your photo. Is that a JTAG USB?
If I only got a USB to TTL dongle, can I still program the chips? Or I need to have a extra JTAG USB?
Because I can only enter the AT mode with the official USB dongle after many trial.

**Comment by lucalauc** [comment]
I found I figure out the problem. The CH340 USB can only communicate the PADI but not program it.
I guess I need to buy a ST-LINK debugger first.
